import Head from 'next/head'
import styles from '../styles/Home.module.css'

import Header from '../components/header/header'

export default function Home() {
  return (
    <>
      <Head>
        <title>Val Fit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.container}>
        <div className={styles.mainLogoContainer}>
          <img src='/val_fit_logo_completo.png' alt='Val Fit' className={styles.mainLogo}/>
          <h2 className={styles.subTitle}>En construccion</h2>
        </div>
        <video className={styles.video} autoPlay loop muted>
          <source src="/video_background.mp4" type="video/mp4" />
        </video>
      </main>
    </>
  )
}
